### ISSUE TITLE
Add solution to "Kth smallest element in Java"

### ISSUE THREAD

**Issue by dudenayak** [mihir0699/Hacktoberfest-2021#21]
I plan to add the question: Kth smallest elements in Java.  
I propose to contribute for this repository by adding this DSA question along with a proper optimized solution in Java.

**Comment by mihir0699** [comment]
Yes, please go ahead

**Comment by dudenayak** [comment]
Could you please add label "hacktoberfest" to it?

**Comment by mihir0699** [comment]
The solution you provided was not optimal
