### ISSUE TITLE
Spiral Matrix

### ISSUE THREAD

**Issue by harshita9621** [mihir0699/Hacktoberfest-2021#40]
Given an m x n matrix, return all elements of the matrix in spiral order
Example:
Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [1,2,3,6,9,8,7,4,5]

**Comment by mihir0699** [comment]
Hi @harshita9621 , do you want to contribute the same?

**Comment by harshita9621** [comment]
@mihir0699 Yes I want to contribute.

**Comment by mihir0699** [comment]
> @mihir0699 Yes I want to contribute.

Please go ahead then

**Comment by harshita9621** [comment]
@mihir0699 Kindly add hacktoberfest label.

**Comment by mihir0699** [comment]
Sorry @harshita9621 , but this problem is already present in the repo, kindly provide PR for the problems that are not present
