### ISSUE TITLE
Binary Tree Right Side View

### ISSUE THREAD

**Issue by harshita9621** [mihir0699/Hacktoberfest-2021#43]
Given the root of a binary tree, imagine yourself standing on the right side of it, return the values of the nodes you can see ordered from top to bottom.

Example:
Input: root = [1,2,3,null,5,null,4]
Output: [1,3,4]

**Comment by harshita9621** [comment]
@mihir0699 Can I contribute?

**Comment by mihir0699** [comment]
Yes pls go ahead

**Comment by mihir0699** [comment]
PR merged, thanks
