### ISSUE TITLE
Same Tree

### ISSUE THREAD

**Issue by harshita9621** [mihir0699/Hacktoberfest-2021#47]
Given the roots of two binary trees p and q, write a function to check if they are the same or not.

Two binary trees are considered the same if they are structurally identical, and the nodes have the same value.

Example:
Input: p = [1,2,3], q = [1,2,3]
Output: true

**Comment by harshita9621** [comment]
@mihir0699 Can I work on this issue.

**Comment by mihir0699** [comment]
Yes, go ahead
